import { Upload, Sparkles, BrainCircuit, CheckCircle } from "lucide-react"
import Image from "next/image"

const steps = [
  { num: "01", icon: Upload, title: "Upload Your Study Material", desc: "Import notes, slides, images, or textbook photos. Reviso AI reads and understands all your study materials instantly." },
  { num: "02", icon: Sparkles, title: "AI Creates Flashcards", desc: "Smart question-answer pairs generated by AI, organized by topic and difficulty. Edit, customize, or regenerate any flashcard." },
  { num: "03", icon: BrainCircuit, title: "Study with Spaced Repetition", desc: "Short daily review sessions powered by spaced repetition science. Watch your knowledge retention and exam scores climb." },
]

export function HowItWorks() {
  return (
    <section id="how-it-works" className="relative border-t border-border/50 px-6 py-32 lg:px-10 lg:py-40">
      <div className="mx-auto max-w-7xl">
        <div className="mb-16 flex flex-col items-start justify-between gap-6 md:flex-row md:items-end">
          <div className="max-w-2xl">
            <p className="mb-6 font-mono text-[11px] uppercase tracking-[0.25em] text-foreground/50">[ 02 / How it works ]</p>
            <h2 className="max-w-3xl text-4xl font-semibold leading-[1.05] tracking-[-0.04em] text-balance sm:text-5xl lg:text-6xl">
              Three steps from <span className="underline decoration-foreground/30 underline-offset-[6px]">page</span> to{" "}
              <span className="underline decoration-foreground/30 underline-offset-[6px]">memory</span>.
            </h2>
          </div>
          <p className="max-w-sm text-pretty text-sm leading-relaxed text-muted-foreground">
            From raw material to long-term memory in three straightforward steps. No setup, no complexity.
          </p>
        </div>

        <div className="grid gap-12 lg:grid-cols-2 lg:gap-20">
          <div className="flex flex-col">
            <div className="space-y-0">
              {steps.map((s, i) => (
                <div key={s.num} className={`flex gap-6 py-7 ${i !== 0 ? "border-t border-border/50" : ""}`}>
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-border/50 bg-card">
                    <s.icon className="h-4 w-4 text-foreground/60" strokeWidth={1.25} />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3">
                      <span className="font-mono text-[11px] uppercase tracking-[0.25em] text-foreground/40">{s.num}</span>
                      <h3 className="text-lg font-semibold tracking-[-0.02em]">{s.title}</h3>
                    </div>
                    <p className="mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">{s.desc}</p>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-xl border border-border/50 bg-card p-5">
              <div className="flex items-center gap-3">
                <CheckCircle className="h-5 w-5 shrink-0 text-emerald-400" strokeWidth={1.5} />
                <p className="text-sm text-muted-foreground">
                  <span className="text-foreground/80">No manual setup needed.</span> Import once, review forever. Your progress is saved locally on your device.
                </p>
              </div>
            </div>
          </div>

          <div className="relative flex items-center justify-center">
            <div className="relative w-[min(80vw,320px)]">
              <div className="absolute inset-0 translate-y-6 rounded-[3rem] bg-black/55 blur-2xl" />
              <div className="relative overflow-hidden">
                <Image
                  src="/reviso-homescreen-mockup.png"
                  alt="Reviso AI flashcard study app with spaced repetition and progress tracking dashboard"
                  width={320}
                  height={640}
                  className="block h-auto w-full select-none"
                />
              </div>
            </div>
            <div className="absolute -bottom-8 left-1/2 -translate-x-1/2 font-mono text-[10px] uppercase tracking-[0.2em] text-foreground/40">
              Daily Review · Dashboard
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
